name: frontend-pipeline
version: 1

source:
  provider: GitHub
  properties:
    branch: main
    repository: https://github.com/bperin/amastay-vue
    connection_name: bperin-github-connection

build:
  image: aws/codebuild/amazonlinux2-aarch64-standard:3.0

stages:
  - name: test
    test_commands:
      - cd amastay-vue
      - npm ci
      - npm run test:unit

  - name: develop
    requires_approval: false
    deploy:
      - name: frontend-app
        env: develop

  - name: staging
    requires_approval: true
    deploy:
      - name: frontend-app
        env: staging

  - name: production
    requires_approval: true
    deploy:
      - name: frontend-app
        env: production
