[tool.poetry]
name = "amastay"
version = "0.1.0"
description = ""
authors = ["Brian Perin <bperin42@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
boto3 = "^1.35.29"
transformers = "^4.45.1"
huggingface-hub = "^0.25.1"
huggingface = "^0.0.1"
httpx = "^0.27.2"
requests = "^2.32.3"
beautifulsoup4 = "^4.12.3"
requests-aws4auth = "^1.3.1"
Flask-Cors = "^5.0.0"
Flask = "^3.0.3"
flask-restx = "^1.3.0"
Flask-JWT-Extended = "^4.6.0"
pytest = "^8.3.3"
selenium = "^4.25.0"
furl = "^2.1.3"
PyJWT = "^2.9.0"
uuid = "^1.30"
python-dotenv = "^1.0.1"
supabase = "^2.8.0"
setuptools = "^75.1.0"
sagemaker = "2.232.1"
pydantic = "^2.9.2"
langchain = "^0.3.1"
geopy = "^2.4.1"
marshmallow = "^3.23.0"
stripe = "^11.1.1"
openapi-generator-cli = "^4.3.1"
undetected-chromedriver = "^3.5.5"
apscheduler = "^3.10.4"
phonenumbers = "^8.13.49"

[tool.poetry.group.dev.dependencies]
pyright = "^1.1.382.post1"

[tool.poetry.scripts]
start = "flask run --host=0.0.0.0 --port=80"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 400
target-version = ['py39']
include = '\.pyi?$'
