version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - curl -sSL https://install.python-poetry.org | python3 -
      - export PATH="/root/.local/bin:$PATH"

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ${AWS_DEFAULT_REGION} | docker login --username AWS --password-stdin ${ECR_REGISTRY}

  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - cd backend-app
      - poetry install --no-root
      - poetry run pytest
      - docker build -t ${IMAGE_URI} -f ../docker/DockerfileBackend .

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push ${IMAGE_URI}
      - printf '{"ImageURI":"%s"}' ${IMAGE_URI} > imageDetail.json
