# Buildspec runs in the build stage of your environment pipeline to generate the environment CloudFormation stack config.
version: 0.2
phases:
  install:
    runtime-versions:
      ruby: 3.2
    commands:
      - cd $CODEBUILD_SRC_DIR
      # Cache the copilot binary using CodeBuild local cache
      - |
        if [ ! -f ~/.local/bin/copilot-linux ]; then
          mkdir -p ~/.local/bin
          wget -q https://ecs-cli-v2-release.s3.amazonaws.com/copilot-linux-v1.34.0 -O ~/.local/bin/copilot-linux
          chmod +x ~/.local/bin/copilot-linux
        fi
      - export PATH=$PATH:~/.local/bin
  build:
    commands:
      - echo "Run your tests"
  post_build:
    commands:
      - export COLOR="false" CI="true"
      # Use jq directly to parse YAML and extract stages - faster than Ruby
      - stages=$(yq e '.stages[].name' copilot/pipelines/amastay-master/manifest.yml)
      # Parallel processing of environment packaging
      - |
        pids=()
        for env in $stages; do
          copilot-linux env package -n $env --output-dir './infrastructure' --upload-assets --force &
          pids+=($!)
        done
        # Wait for all parallel processes and check their exit status
        for pid in "${pids[@]}"; do
          wait $pid || exit 1
        done
cache:
  paths:
    - ~/.local/bin/**/*
artifacts:
  files:
    - "infrastructure/*"
