# The manifest for the "amastay-master" pipeline.
# This YAML file defines your pipeline: the source repository it tracks and the order of the environments to deploy to.
# For more info: https://aws.github.io/copilot-cli/docs/manifest/pipeline/

# The name of the pipeline.
name: amastay-master

# The version of the schema used in this template.
version: 1

# This section defines your source, changes to which trigger your pipeline.
source:
  # The name of the provider that is used to store the source artifacts.
  # (i.e. GitHub, Bitbucket, CodeCommit)
  provider: GitHub
  # Additional properties that further specify the location of the artifacts.
  properties:
    branch: master
    repository: https://github.com/bperin/amastay
    # Optional: specify the name of an existing CodeStar Connections connection.
    connection_name: copilot-bperi-amastay

# This section defines the order of the environments your pipeline will deploy to.
stages:
  - name: develop
    deployments:
      deploy-env:
        template_path: infrastructure/develop.env.yml
        template_config: infrastructure/develop.env.params.json
        stack_name: backend-develop
        release: true
        post_deploy:
          commands:
            - copilot svc deploy --name api --env develop --force

  - name: staging
    deployments:
      deploy-env:
        template_path: infrastructure/staging.env.yml
        template_config: infrastructure/staging.env.params.json
        stack_name: backend-staging
        release: true
        post_deploy:
          commands:
            - copilot svc deploy --name api --env staging --force

  - name: production
    deployments:
      deploy-env:
        template_path: infrastructure/production.env.yml
        template_config: infrastructure/production.env.params.json
        stack_name: backend-production
        release: true
        post_deploy:
          commands:
            - copilot svc deploy --name api --env production --force
    requires_approval: true
