# The manifest for the "amastay-master" pipeline.
# This YAML file defines your pipeline: the source repository it tracks and the order of the environments to deploy to.
# For more info: https://aws.github.io/copilot-cli/docs/manifest/pipeline/

# The name of the pipeline.
name: amastay-master

# The version of the schema used in this template.
version: 1

# This section defines your source, changes to which trigger your pipeline.
source:
  # The name of the provider that is used to store the source artifacts.
  # (i.e. GitHub, Bitbucket, CodeCommit)
  provider: GitHub
  # Additional properties that further specify the location of the artifacts.
  properties:
    branch: master
    repository: https://github.com/bperin/amastay
    connection_arn: arn:aws:codeconnections:us-east-2:422220778159:connection/08d374d7-a6c6-4be2-adf9-5d4ffa5e8ced

build:
  image: aws/codebuild/amazonlinux2-x64-standard:4.0

# This section defines the order of the environments your pipeline will deploy to.
stages:
  - # The name of the environment.
    name: develop
    deployments:
      deploy-env:
        template_path: infrastructure/develop.env.yml
        template_config: infrastructure/develop.env.params.json
        stack_name: amastay-backend-develop
    # Optional: flag for manual approval action before deployment.
    # requires_approval: true
    # Optional: use test commands to validate this stage of your build.
    # test_commands: [echo 'running tests', make test]

  - # The name of the environment.
    name: staging
    deployments:
      deploy-env:
        template_path: infrastructure/staging.env.yml
        template_config: infrastructure/staging.env.params.json
        stack_name: amastay-backend-staging
    # Optional: flag for manual approval action before deployment.
    # requires_approval: true
    # Optional: use test commands to validate this stage of your build.
    # test_commands: [echo 'running tests', make test]

  - # The name of the environment.
    name: production
    deployments:
      deploy-env:
        template_path: infrastructure/production.env.yml
        template_config: infrastructure/production.env.params.json
        stack_name: amastay-backend-production
    # Optional: flag for manual approval action before deployment.
    # requires_approval: true
    # Optional: use test commands to validate this stage of your build.
    # test_commands: [echo 'running tests', make test]
