name: Deploy to AWS

on:
  push:
    branches:
      - master
      - staging
      - develop  # Trigger on pushes to master, staging, and develop branches

env:
  AWS_REGION: us-east-1
  APP_NAME: amastay

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install Copilot CLI
        run: |
          curl -Lo copilot https://github.com/aws/copilot-cli/releases/latest/download/copilot-linux
          chmod +x copilot
          sudo mv copilot /usr/local/bin/copilot
          copilot --version

      - name: Deploy to AWS
        run: |
          # Deploy to different environments based on branch
          if [ "${{ github.ref }}" = "refs/heads/master" ]; then
            copilot deploy --env production
          elif [ "${{ github.ref }}" = "refs/heads/staging" ]; then
            copilot deploy --env staging
          elif [ "${{ github.ref }}" = "refs/heads/develop" ]; then
            copilot deploy --env develop
          fi